[phases.setup]
nixPkgs = ["python311", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    "source /opt/venv/bin/activate && pip install --upgrade pip",
    "source /opt/venv/bin/activate && pip install -r requirements.txt",
    "source /opt/venv/bin/activate && python -c 'import django; print(f\"Django {django.get_version()} installed successfully\")'"
]

[phases.build]
cmds = [
    "echo 'Build phase: Verifying virtual environment'",
    "ls -la /opt/venv/bin/",
    "source /opt/venv/bin/activate && python -c 'import sys; print(\"Python path:\", sys.path)'",
    "source /opt/venv/bin/activate && python -c 'import django; print(\"Django version:\", django.get_version())'"
]

[start]
cmd = "bash start.sh"
