# Generated by Django 5.2.4 on 2025-08-02 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("recommendation", models.CharField(max_length=10)),
                ("explanation", models.TextField()),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_tolerance",
                    models.IntegerField(
                        default=3, help_text="1=Conservative, 5=Aggressive"
                    ),
                ),
                (
                    "investment_horizon",
                    models.IntegerField(default=5, help_text="Time in years"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
